# テスト用
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:algolearn
    username: 
    password: 
    driverClassName: org.h2.Driver
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
prglanguage: 
  java: 
    fileName: Test.java
    buildFileName: Test
    buildCmdPath: F:\\dev\\AdoptOpenJDK\\jdk-8.0.202.08\\bin\\javac
    executeCmdPath: F:\\dev\\AdoptOpenJDK\\jdk-8.0.202.08\\bin\\java
    workFolderPath: F:\\workfolder
  ccpp: 
    fileName: 
    buildFileName: 
    buildCmdPath: 
    executeCmdPath:
    workFolderPath:
  python: 
    fileName: 
    buildFileName: 
    buildCmdPath:
    executeCmdPath:
    workFolderPath:
server:
  charactercode: utf-8
